
// Posts

export type LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_START = "LOAD_POSTS_START";

export type LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";

export type CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_START = "CREATE_POST_START";

export type CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export type EDIT_POST_START = "EDIT_POST_START";
export const EDIT_POST_START = "EDIT_POST_START";

export type EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

export type DELETE_POST_START = "DELETE_POST_START";
export const DELETE_POST_START = "DELETE_POST_START";

export type DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

// Comments

export type LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";

export type LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";

export type CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_START = "CREATE_COMMENT_START";

export type CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export type EDIT_COMMENT_START = "EDIT_COMMENT_START";
export const EDIT_COMMENT_START = "EDIT_COMMENT_START";

export type EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export type DELETE_COMMENT_START = "DELETE_COMMENT_START";
export const DELETE_COMMENT_START = "DELETE_COMMENT_START";

export type DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
