
// Posts

export type LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_START = "LOAD_POSTS_START";

export type LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";

export type LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE";
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE";

export type CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_START = "CREATE_POST_START";

export type CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export type CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export type EDIT_POST_START = "EDIT_POST_START";
export const EDIT_POST_START = "EDIT_POST_START";

export type EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

export type EDIT_POST_FAILURE = "EDIT_POST_FAILURE";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";

export type DELETE_POST_START = "DELETE_POST_START";
export const DELETE_POST_START = "DELETE_POST_START";

export type DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export type DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

// Comments

export type LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";

export type LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";

export type LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE";
export const LOAD_COMMENTS_FAILURE = "LOAD_COMMENTS_FAILURE";

export type CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_START = "CREATE_COMMENT_START";

export type CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export type CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export type EDIT_COMMENT_START = "EDIT_COMMENT_START";
export const EDIT_COMMENT_START = "EDIT_COMMENT_START";

export type EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export type EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE";
export const EDIT_COMMENT_FAILURE = "EDIT_COMMENT_FAILURE";

export type DELETE_COMMENT_START = "DELETE_COMMENT_START";
export const DELETE_COMMENT_START = "DELETE_COMMENT_START";

export type DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export type DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";


// Both posts and comments

export type VOTE_START = "VOTE_START";
export const VOTE_START = "VOTE_START";

export type VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_SUCCESS = "VOTE_SUCCESS";

export type VOTE_FAILURE = "VOTE_FAILURE";
export const VOTE_FAILURE = "VOTE_FAILURE";
