export type LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_START = "LOAD_POSTS_START";

export type LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";

export type LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";

export type LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";

export type CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_START = "CREATE_POST_START";

export type CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";